### PR TITLE
Fixed issue with image deletion on cloudinary for leads

### LINKED ISSUE #229: Deleting the images from cloudinary for leads
### Is there an existing issue for this?

- [x] I have searched and didn't find similar issue

### Describe your issue

On deleting any leads their images are not being deleted from the database

### Steps to reproduce

1. Go to [leads page](https://www.pointblank.club/leads)

### What was the expected result?

On deleting the leads their images should also be deleted from the cloudinary

### Insert any pictures or video demonstrating the issue. (optional)

Image
Example from the events page

### PR DESCRIPTION
**Pull request by ShreyashSri**
On deleting leads, their image will also be deleted from cloudinary

## Which issue(s) this PR fixes:

Fixes #229

## Changes Made
Describe the changes you've made in this PR:
- ✅ Bug fix

## Type of Change
- ✅ Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: app/(default)/api/leads/route.ts [hunk 1]
```diff
@@ -218,21 +219,54 @@ export async function DELETE(request: Request) {
...
     }
 
-    return NextResponse.json({ id }, { status: 200 });
-  } catch (error) {
-    console.error("Error deleting lead:", error);
+    // If there's an image URL, delete it from Cloudinary
+    if (deletedLead.imageURL) {
+      try {
+        // Extract public_id from the Cloudinary URL
+        const matches = deletedLead.imageURL.match(/\/v\d+\/(.+?)\./);
```
Comment (alfiyafatima09) [inline app/(default)/api/leads/route.ts:230]: * Verify whether all Cloudinary image URLs contain a version v/.  
* If versions are inconsistent, update the extraction logic accordingly.

File: app/(default)/api/leads/route.ts [hunk 2]
```diff
@@ -218,21 +219,54 @@ export async function DELETE(request: Request) {
...
+        const publicId = matches ? matches[1] : null;
+
+        if (publicId) {
+          console.log('Attempting to delete image with public ID:', publicId);
```
Comment (alfiyafatima09) [inline app/(default)/api/leads/route.ts]: Remove console logs before merging to production [console.log]

**Review by alfiyafatima09 — CHANGES_REQUESTED** [review]
Suggested improvements for Cloudinary image deletion logic[regex] and console logs removal. Please verify URL versioning consistency before merging.

File: app/(default)/api/leads/route.ts (hunk 1 above)
Comment (ShreyashSri) [reply app/(default)/api/leads/route.ts:230]: Verified it. All the Cloudinary image URLs will contain a version of v/

**Review by alfiyafatima09 — COMMENTED** [review]
lgtm!
