### PR TITLE
Fixed Achievements page and Admin issue

### LINKED ISSUE #264: Fetch option not working on achievements page
### Is there an existing issue for this?

- [x] I have searched and didn't find similar issue

### Describe your issue

Unable to edit achievements, also no option for deleting them

### Steps to reproduce

1. Go to Achievements page
2. Login as Admin
3. Click on Edit Achievements

### What was the expected result?

_No response_

### Insert any pictures or video demonstrating the issue. (optional)

Image

### PR DESCRIPTION
**Pull request by ShreyashSri**
## Summary:  What does this PR do?

- Fixed admin issue
- Fixed achievements page fetch not working
- Added delete option for achievements
- Added Image edit option
- Added the apis to swagger

## Which issue(s) this PR fixes:

Fixes #264

## Changes Made
Describe the changes you've made in this PR:
- [x] Feature implementation
- [x] Bug fix
- [x] Documentation update
- [ ] Code refactoring
- [ ] Configuration changes
- [ ] Other (please specify)

## Type of Change
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Documentation update
- [ ] Performance improvement
- [ ] Code cleanup or refactor

## Screenshots (if applicable)
- Page
image
- Edit:
image

## Documentation
- [x] I have updated the documentation accordingly
- [ ] Documentation update is not required

### CODE REVIEW

**Comment by ShreyashSri** [comment]
@mohit-nagaraj @alfiyafatima09 review pls

File: app/(default)/api/achievements/route.ts [hunk 1]
```diff
@@ -421,3 +583,97 @@ export async function PUT(request: Request) {
     );
   }
 }
+
+// DELETE method: Delete an achievement based on name
```
Comment (alfiyafatima09) [inline app/(default)/api/achievements/route.ts]: Can we check through email/some unique-id instead ?

**Review by alfiyafatima09 — CHANGES_REQUESTED** [review]
can you use a unique id even during deletion?

File: app/(default)/api/achievements/route.ts (hunk 1 above)
Comment (ShreyashSri) [reply app/(default)/api/achievements/route.ts]: used email for searching/editing instead of name

**Review by alfiyafatima09 — APPROVED** [review]
lgtm
